name: Perseus Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: "34"  # 指定 Android SDK 版本
          build-tools: "33.0.2"  # 指定 Build Tools 版本

      - name: Build Perseus APK
        run: ./patch_perseus.sh

      - name: Zipalign and Sign Android release
        run: ./zipalign_sign.sh
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}  # 确保 Android SDK 路径可用
          PATH: ${{ env.ANDROID_HOME }}/build-tools/33.0.2:${{ env.PATH }}  # 添加 Build Tools 到 PATH

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Perseus Release"
          files: |
            build/*.apk
